spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/numble?serverTimezone=Asia/Seoul
    username: numble
    password: password

redis:
  address: redis://localhost:6379
