spring:
  application:
    name: numble-reservation
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: secret-key
  issuer: numble
  valid-duration-second: 86400
